- name: Installing redis repo from remote rpm
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true

- name: Enable Redis 6 Version
  ansible.builtin.shell: yum module enable redis:remi-6.2 -y

- name: Installing  Redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Update Redis Listen Address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Update redis Listen Address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting redis service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: true

