- name: Configuring yum repos for rabbitmq
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash ; curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Installing rabbitmq
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: Enabling rabbitmq service
  ansible.builtin.systemd:
    name: rabbitmq-server
    enabled: true
    state: started

#- name: Add Application User
#  community.rabbitmq.rabbitmq_user:
#    user: "{{ lookup('amazon.aws.aws_ssm', 'roboshop.{{env}}.rabbitmq.amqp_user', region='us-east-1') }}"
#    password: "{{ lookup('amazon.aws.aws_ssm', 'roboshop.dev.rabbitmq.amqp_pass', region='us-east-1') }}"
#    vhost: /
#    configure_priv: .*
#    read_priv: .*
#    write_priv: .*
#    state: present

- name: Add Application User
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('amazon.aws.aws_ssm', 'roboshop.{{env}}.rabbitmq.amqp_user', region='us-east-1') }}"
    password: "roboshop123"
   # "{{ lookup('amazon.aws.aws_ssm', 'roboshop.{{env}}.rabbitmq.amqp_pass', region='us-east-1') }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present