- name :  Copying elastic repo file
  ansible.builtin.template:
    src : elastic
    dest : /etc/yum.repos.d/elastic.repo

- name : Installing filebeat
  ansible.builtin.systemd:
    name : filebeat
    state : installed


- name : Copying Filebeat configuration file
  ansible.builtin.template:
    src : filebeat.yml
    dest : /etc/filebeat/filebeat.yml

- name : Restarting Filebeat service
  ansible.builtin.systemd:
    state : restarted
    enabled : true


