- name : Copying Logstash configuration file
  ansible.builtin.template:
    src : logstash.conf
    dest : /etc/logstash/conf.d/logstash.conf

- name : Restarting Logstash service
  ansible.builtin.systemd:
    name : logstash
    state : restarted
    enabled : true
