- name: Configuring NodeJS Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing nodeJS
  ansibile.builtin.yum:
    name: nodejs
    state: installed

- name: Adding Roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Removing app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes

- name: Installing Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Setting up service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Starting systemd services
  ansible.builtin.systemd:
    name: catalogue
    daemon_reload: true
    enabled: true
    state: started

- name: Copying mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing MongoDB
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

-name: Loading schema
 ansible.builtin.shell: mongo --host mongodb-dev.devopskumar.site  </app/schema/catalogue.js






