- name: Installing golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Loading Application setup
  ansible.builtin.import_tasks:
    file: app_setup.yml

- name: Installing dependencies
  ansible.builtin.shell: go mod init dispatch ;  go get ;  go build

- name: Loading Systemd service
  ansible.builtin.import_tasks:
    file: systemd_service_setup.yml