- name: Setting up service
  ansible.builtin.copy:
    src: {{ component}}.service
    dest: /etc/systemd/system/{{ component}}.service

- name: Starting systemd services
  ansible.builtin.systemd:
    name: {{ component}}
    daemon_reload: true
    enabled: true
    state: started